// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// NormalizeMatrixCpp
NumericMatrix NormalizeMatrixCpp(const NumericMatrix& x, const NumericVector& means, const NumericVector& sds, const int numThreads);
RcppExport SEXP _adanear_NormalizeMatrixCpp(SEXP xSEXP, SEXP meansSEXP, SEXP sdsSEXP, SEXP numThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type means(meansSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sds(sdsSEXP);
    Rcpp::traits::input_parameter< const int >::type numThreads(numThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(NormalizeMatrixCpp(x, means, sds, numThreads));
    return rcpp_result_gen;
END_RCPP
}
// DenormalizeMatrixCpp
NumericMatrix DenormalizeMatrixCpp(const NumericMatrix& x, const NumericVector& means, const NumericVector& sds, const int numThreads);
RcppExport SEXP _adanear_DenormalizeMatrixCpp(SEXP xSEXP, SEXP meansSEXP, SEXP sdsSEXP, SEXP numThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type means(meansSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sds(sdsSEXP);
    Rcpp::traits::input_parameter< const int >::type numThreads(numThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(DenormalizeMatrixCpp(x, means, sds, numThreads));
    return rcpp_result_gen;
END_RCPP
}
// AdasynInterpolateCpp
NumericMatrix AdasynInterpolateCpp(const NumericMatrix& minMat, const IntegerVector& anchorIdx, const IntegerVector& neighborIdx, const NumericVector& lambdas, const int numThreads);
RcppExport SEXP _adanear_AdasynInterpolateCpp(SEXP minMatSEXP, SEXP anchorIdxSEXP, SEXP neighborIdxSEXP, SEXP lambdasSEXP, SEXP numThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type minMat(minMatSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type anchorIdx(anchorIdxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type neighborIdx(neighborIdxSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< const int >::type numThreads(numThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(AdasynInterpolateCpp(minMat, anchorIdx, neighborIdx, lambdas, numThreads));
    return rcpp_result_gen;
END_RCPP
}
// ComputeDifficultyCpp
NumericVector ComputeDifficultyCpp(const IntegerMatrix& knnIdx, const IntegerVector& minGlobalIdx, const IntegerVector& yBinary, const int numThreads);
RcppExport SEXP _adanear_ComputeDifficultyCpp(SEXP knnIdxSEXP, SEXP minGlobalIdxSEXP, SEXP yBinarySEXP, SEXP numThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type knnIdx(knnIdxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type minGlobalIdx(minGlobalIdxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type yBinary(yBinarySEXP);
    Rcpp::traits::input_parameter< const int >::type numThreads(numThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeDifficultyCpp(knnIdx, minGlobalIdx, yBinary, numThreads));
    return rcpp_result_gen;
END_RCPP
}
// SampleNeighborsCpp
IntegerVector SampleNeighborsCpp(const IntegerMatrix& knnLocal, const IntegerVector& anchorLocalIdx);
RcppExport SEXP _adanear_SampleNeighborsCpp(SEXP knnLocalSEXP, SEXP anchorLocalIdxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type knnLocal(knnLocalSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type anchorLocalIdx(anchorLocalIdxSEXP);
    rcpp_result_gen = Rcpp::wrap(SampleNeighborsCpp(knnLocal, anchorLocalIdx));
    return rcpp_result_gen;
END_RCPP
}
// RestoreTypesCpp
void RestoreTypesCpp(NumericMatrix& synMat, const IntegerVector& binCols, const IntegerVector& intCols, const IntegerVector& nnIntCols, const int numThreads);
RcppExport SEXP _adanear_RestoreTypesCpp(SEXP synMatSEXP, SEXP binColsSEXP, SEXP intColsSEXP, SEXP nnIntColsSEXP, SEXP numThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type synMat(synMatSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type binCols(binColsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type intCols(intColsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type nnIntCols(nnIntColsSEXP);
    Rcpp::traits::input_parameter< const int >::type numThreads(numThreadsSEXP);
    RestoreTypesCpp(synMat, binCols, intCols, nnIntCols, numThreads);
    return R_NilValue;
END_RCPP
}
// NearMissAvgDistCpp
NumericVector NearMissAvgDistCpp(const NumericMatrix& distMat, const int numThreads);
RcppExport SEXP _adanear_NearMissAvgDistCpp(SEXP distMatSEXP, SEXP numThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type distMat(distMatSEXP);
    Rcpp::traits::input_parameter< const int >::type numThreads(numThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(NearMissAvgDistCpp(distMat, numThreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adanear_NormalizeMatrixCpp", (DL_FUNC) &_adanear_NormalizeMatrixCpp, 4},
    {"_adanear_DenormalizeMatrixCpp", (DL_FUNC) &_adanear_DenormalizeMatrixCpp, 4},
    {"_adanear_AdasynInterpolateCpp", (DL_FUNC) &_adanear_AdasynInterpolateCpp, 5},
    {"_adanear_ComputeDifficultyCpp", (DL_FUNC) &_adanear_ComputeDifficultyCpp, 4},
    {"_adanear_SampleNeighborsCpp", (DL_FUNC) &_adanear_SampleNeighborsCpp, 2},
    {"_adanear_RestoreTypesCpp", (DL_FUNC) &_adanear_RestoreTypesCpp, 5},
    {"_adanear_NearMissAvgDistCpp", (DL_FUNC) &_adanear_NearMissAvgDistCpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_adanear(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
