# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Normaliza uma matriz numerica em paralelo
NULL

NormalizeMatrixCpp <- function(x, means, sds, numThreads) {
    .Call('_sattvaR_NormalizeMatrixCpp', PACKAGE = 'sattvaR', x, means, sds, numThreads)
}

DenormalizeMatrixCpp <- function(x, means, sds, numThreads) {
    .Call('_sattvaR_DenormalizeMatrixCpp', PACKAGE = 'sattvaR', x, means, sds, numThreads)
}

AdasynInterpolateCpp <- function(minMat, anchorIdx, neighborIdx, lambdas, numThreads) {
    .Call('_sattvaR_AdasynInterpolateCpp', PACKAGE = 'sattvaR', minMat, anchorIdx, neighborIdx, lambdas, numThreads)
}

ComputeDifficultyCpp <- function(knnIdx, minGlobalIdx, yBinary, numThreads) {
    .Call('_sattvaR_ComputeDifficultyCpp', PACKAGE = 'sattvaR', knnIdx, minGlobalIdx, yBinary, numThreads)
}

SampleNeighborsCpp <- function(knnLocal, anchorLocalIdx) {
    .Call('_sattvaR_SampleNeighborsCpp', PACKAGE = 'sattvaR', knnLocal, anchorLocalIdx)
}

RestoreTypesCpp <- function(synMat, binCols, intCols, nnIntCols, numThreads) {
    invisible(.Call('_sattvaR_RestoreTypesCpp', PACKAGE = 'sattvaR', synMat, binCols, intCols, nnIntCols, numThreads))
}

NearMissAvgDistCpp <- function(distMat, numThreads) {
    .Call('_sattvaR_NearMissAvgDistCpp', PACKAGE = 'sattvaR', distMat, numThreads)
}

