# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Normaliza uma matriz numerica em paralelo
NULL

NormalizeMatrixCpp <- function(x, means, sds, numThreads) {
    .Call('_adanear_NormalizeMatrixCpp', PACKAGE = 'adanear', x, means, sds, numThreads)
}

DenormalizeMatrixCpp <- function(x, means, sds, numThreads) {
    .Call('_adanear_DenormalizeMatrixCpp', PACKAGE = 'adanear', x, means, sds, numThreads)
}

AdasynInterpolateCpp <- function(minMat, anchorIdx, neighborIdx, lambdas, numThreads) {
    .Call('_adanear_AdasynInterpolateCpp', PACKAGE = 'adanear', minMat, anchorIdx, neighborIdx, lambdas, numThreads)
}

ComputeDifficultyCpp <- function(knnIdx, minGlobalIdx, yBinary, numThreads) {
    .Call('_adanear_ComputeDifficultyCpp', PACKAGE = 'adanear', knnIdx, minGlobalIdx, yBinary, numThreads)
}

SampleNeighborsCpp <- function(knnLocal, anchorLocalIdx) {
    .Call('_adanear_SampleNeighborsCpp', PACKAGE = 'adanear', knnLocal, anchorLocalIdx)
}

RestoreTypesCpp <- function(synMat, binCols, intCols, nnIntCols, numThreads) {
    invisible(.Call('_adanear_RestoreTypesCpp', PACKAGE = 'adanear', synMat, binCols, intCols, nnIntCols, numThreads))
}

NearMissAvgDistCpp <- function(distMat, numThreads) {
    .Call('_adanear_NearMissAvgDistCpp', PACKAGE = 'adanear', distMat, numThreads)
}

